name: local
variables:
  - name: baseUrl
    value: http://localhost:5000/api
  - name: phone
    value: "0770000000"
  - name: password
    value: "111111"
  - name: userId
    value: "6"
  - name: vehicleId
    value: "1"
