import CancelRounded from '@mui/icons-material/CancelRounded'
import Inventory2Rounded from '@mui/icons-material/Inventory2Rounded'
import AcUnitRounded from '@mui/icons-material/AcUnitRounded'
import { optionBlocker, type AllocationOption, type ConfirmedOrder } from '../data'

export function VehicleOption({ order, option, selected, onSelect }: { order: ConfirmedOrder; option: AllocationOption; selected: boolean; onSelect: () => void }) {
  const blocker = optionBlocker(order, option)
  const CargoIcon = order.requirement === 'Chilled' ? AcUnitRounded : Inventory2Rounded
  const weightCapacity = option.weightCapacity?.toLocaleString('en-US')
  return <label className={`order-vehicle-option ${selected ? 'order-vehicle-option--selected' : ''} ${blocker ? 'order-vehicle-option--blocked' : ''}`}>
    <div className="order-option-heading"><input type="radio" name={`vehicle-for-${order.id}`} value={option.id} checked={selected} disabled={!!blocker} onChange={onSelect} aria-describedby={blocker ? `${option.id}-reason` : undefined} /><div className="order-option-title"><strong className="type-text-sm-bold">{option.vehicleId} · {option.trip}</strong><span className="type-text-xs-regular text-wp-text-secondary">{option.type} · {option.depot}</span></div><span className={`order-eligibility type-text-xs-medium ${blocker ? 'order-eligibility--blocked' : ''}`}>{blocker ? <CancelRounded fontSize="inherit" /> : <CargoIcon fontSize="inherit" />}{blocker ? 'Not eligible' : order.requirement}</span></div>
    {blocker ? <p id={`${option.id}-reason`} className="order-option-reason type-text-xs-regular text-wp-text-tertiary">{blocker}</p> : <div className="order-option-preview"><p className="type-text-xs-semibold text-wp-text-secondary">After assignment</p><div className="order-capacity-metrics"><div><p className="type-text-xs-regular"><span className="text-wp-text-secondary">Weight</span><strong className="type-text-xs-semibold">{order.weight + option.usedWeight!} / {weightCapacity} kg</strong></p><progress max={option.weightCapacity!} value={order.weight + option.usedWeight!} aria-label={`Weight after assignment to ${option.vehicleId}`} /></div><div><p className="type-text-xs-regular"><span className="text-wp-text-secondary">Volume</span><strong className="type-text-xs-semibold">{Math.round((order.volume + option.usedVolume!) * 1000) / 1000} / {option.volumeCapacity} m³</strong></p><progress max={option.volumeCapacity!} value={order.volume + option.usedVolume!} aria-label={`Volume after assignment to ${option.vehicleId}`} /></div></div><dl className="order-assignment-facts type-text-xs-regular"><div><dt className="text-wp-text-secondary">Planned arrival</dt><dd>{option.arrival} · Within window</dd></div><div><dt className="text-wp-text-secondary">Fuel</dt><dd>{option.fuelRequired} L required / {option.fuelRemaining} L remaining</dd></div><div><dt className="text-wp-text-secondary">Daily trips</dt><dd>{option.dailyTripsAfter} / {option.dailyTripLimit}</dd></div></dl></div>}
  </label>
}
