events {}

http {
  server {
    listen 80;

    # Van endpoint
    location /route/v1/van/ {
      proxy_pass http://osrm-van:5000/route/v1/driving/;
    }

    # Truck endpoint
    location /route/v1/truck/ {
      proxy_pass http://osrm-truck:5000/route/v1/driving/;
    }
  }
}